### ISSUE TITLE
请问大神oc选择什么机型，您替换的网卡具体是什么型号？

### ISSUE THREAD

**Issue by cartercch** [takobaba/EFI-Opencore-Thinkpad-L490#2]
大神，您好！
用您的efi我已经有一段时间，最近再次看到又有更新，非常感谢。不知现在版本应该选择哪个机型？我选了基本cpu相近的，有些usb全部不能用，有些type c不能用。能否告知您选的是哪个机型？
还有从看到您换了博通的网卡，不知您换的是哪个型号？联想的机子换网卡是不是有白名单限制，不知您是怎么解决的？
不知能否qq联系您，请教使用相关细节？我的qq：87262029

**Comment by takobaba** [comment]
Please message me in English, I had to translate your message:

`God, hello!
I've been using your efi for a while and saw it again recently and got an update, thank you very much. I don't know which model should I choose for the current version? I chose the one with a similar basic cpu, some usbs can't be used at all, and some type c can't be used. Can you tell me which model you chose?
Also, since I saw that you changed the network card of Broadcom, which model did you change? Is there a whitelist restriction for changing the network card of Lenovo's machine? I wonder how you solved it?
I don't know if I can contact you on qq and ask for relevant details? My qq: 87262029`

You might need to map your own USBs. I am dropping some helpful links:
- https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html
- https://www.reddit.com/r/hackintosh/comments/ta1ef4/guide_easy_usb_mapping_with_usbtoolbox_on_windows/
- https://github.com/corpnewt/USBMap

I got Broadcom BCM4390 off AliExpress
https://www.aliexpress.com/item/4000632365086.html

for wifi and bluetooth, have a read here:
https://dortania.github.io/Wireless-Buyers-Guide/unsupported.html
https://www.tonymacx86.com/threads/broadcom-wifi-bluetooth-guide.242423/
https://github.com/toleda/wireless_broadcom

**Comment by cartercch** [comment]
Dear Sir or Madam,
I’m very glad to find that you’ve updated OC and your EFI is ready for Ventura. I’m writing to you just want to know which model you are using in platforminfo. For I’ve tried macbook pro 15,1 to macbook pro 15,4 and my L490 could only work in macbook pro 15,4. For example if I choose macbook pro 15,1, the usb failed. Would you please tell me which model do you use?
Moreover, I’ve test CPU frequency with intel power Gadget. The CPU frequency in my Ventura is 2.5 above and is much higher than that in Win11. What about yours?
 
Looking forward to receive your reply.
 
Yours
 
Carter

**Comment by takobaba** [comment]
I updated the EFI I m gonna upload now which improves the CPU results a lot.

**Comment by takobaba** [comment]
Check the latest committed EFI and replace yours. Make sure you play with CPU friend.
